### ISSUE TITLE
Shard name does not match dependency name

### ISSUE THREAD

**Issue by ghost** [madeindjs/Crystagiri#19]
Here is my terminal output
```
➜ shards install
Resolving dependencies
Fetching https://github.com/madeindjs/crystagiri.git
Error shard name (cristagiri) doesn't match dependency name (crystagiri)
```
My `shard.yml`
```
...
dependencies:
  crystagiri:
    github: madeindjs/crystagiri
...
```
Please fix this.

**Comment by madeindjs** [comment]
This is really strange because [I already fixed that](https://github.com/madeindjs/Crystagiri/commit/d6c9647dbcb73a63013b3fb0a9e9cb2246e108b3). I tried in a new project and I had no problem:

~~~bash
$ crystal init app azerty
$ # add dependencies
$ shards install
Resolving dependencies
Fetching https://github.com/madeindjs/crystagiri.git
Installing crystagiri (0.3.5)
Writing shard.lock
~~~

Wich version of Crystal do you use ? Also did you tried to fix version ?

~~~yml
dependencies:
  crystagiri:
    github: madeindjs/crystagiri
    version: 0.3.5
~~~

**Comment by ghost** [comment]
Here is my terminal output
```bash
➜ crystal --version && shards --version
Crystal 0.34.0 (2020-04-12)

LLVM: 10.0.0
Default target: x86_64-pc-linux-gnu
Shards 0.9.0 (2019-08-06)
```
I used Ruby, recently came to Crystal. I just used the `installation` part in your `README.md`, which did not contain the `version` line.
After adding it, everything is fine now.
Thank you, @madeindjs
