### ISSUE TITLE
Parsing with different IPs?

### ISSUE THREAD

**Issue by nik736** [madeindjs/Crystagiri#6]
Great library! 

I am new to Crystal and I am wondering how one would use your library with multiple IPs? With curl I can simply add a --interface parameter, is something like this possible with Crystagiri?

Thanks

**Comment by madeindjs** [comment]
For the moment it's not possible with [`Crystagiri::HTML.from_url`][from_url] because [`from_url`][from_url] method only take URL argument (no configuration).

[`from_url`][from_url] simply use [`http/client`][client] standard library to get retreive HTML content. So I think you have two solutions:

* Retreive HTML content with your custom [`http/client`][client] then use [`Crystagiri::HTML.new`][new]
* Implement a new method [`Crystagiri::HTML.from_url`][from_url] who allow some parameter

If you think you can do the second method I will accept your MR with pleasure :smile: 

[from_url]: https://github.com/madeindjs/Crystagiri/blob/master/src/crystagiri/html.cr#L11
[client]: https://crystal-lang.org/api/0.24.1/HTTP/Client.html
[new]: https://github.com/madeindjs/Crystagiri/blob/master/src/crystagiri/html.cr#L47

**Comment by madeindjs** [comment]
Closed because of inactivity
